// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvK4YcbADt4W1LwcZ3hTAJizOp1Yq4mic',
    appId: '1:464529924086:web:7bfd3c36c3dcafcab431d7',
    messagingSenderId: '464529924086',
    projectId: 'healthyguppy-95a43',
    authDomain: 'healthyguppy-95a43.firebaseapp.com',
    storageBucket: 'healthyguppy-95a43.firebasestorage.app',
    measurementId: 'G-JESYHRFG3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyActIy26pwjmR2jrUIe5mIbRozs2NCW3T4',
    appId: '1:464529924086:android:0e40b890d90dad19b431d7',
    messagingSenderId: '464529924086',
    projectId: 'healthyguppy-95a43',
    storageBucket: 'healthyguppy-95a43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLHDFoKMK_yJYr9gqyd_Ae9VJ2Sh4UUOY',
    appId: '1:464529924086:ios:783bad84a87433b2b431d7',
    messagingSenderId: '464529924086',
    projectId: 'healthyguppy-95a43',
    storageBucket: 'healthyguppy-95a43.firebasestorage.app',
    iosBundleId: 'com.example.healthyguppy',
  );
}
